messages:
  console_prefix: "§A<§6@§EQuantara§A> §7"
  prefix: "§8[§9Quantara§8] §7"

  system:
    onEnable: "§A<§6@§EQuantara§A> §7Le plugin a bien été démarré."
    onDisable: "§A<§6@§EQuantara§A> §7Le plugin a bien été éteint."

settings:
  debug_mode: true
  duplicate_profil: true

max-homes-per-player: 5
home-teleport-cooldown-seconds: 30
save-interval-seconds: 60

qprofils:
