name: Quantara
version: 1.0
main: fr.tableikea.quantara.Main
api-version: 1.20
authors:
  - TableIkea_
  - Lorenzo60
depend:
  - QuantaraAuth
commands:
  createprofile:
    aliases:
      - forceprofil
      - fcp
    description: "Force la création d'un profil pour un joueur désigné."
    permission: "admin.use"
  checkprofile:
    aliases:
      - checkplayer
      - check
      - lookup
    description: "Affiche les informations du joueur désigné."
    permission: "moderateur.use"
  removeprofile:
    aliases:
      - frp
    description: "Force la suppression d'un profil pour un joueur désigné."
    permission: "admin.use"
  reloadconfig:
    aliases:
      - rlc
    description: "Recharge la configuration du serveur."
    permission: "moderateur.use"
  mod:
    aliases:
      - annonce
      - broadcast
    description: "Publie un message sur tout le serveur."
    permission: "moderateur.use"
  color:
    aliases:
      - showcolor
    description: "Affiche les couleurs disponible dans Minecraft pour les textes."
    permission: "vip.use"
  perm:
    aliases:
      - changeperm
      - permission
      - rank
      - grade
    description: "Change le grade d'un joueur désigné."
    permission: "admin.use"
  restartserver:
    aliases:
      - rs
    description: "Redémarre le serveur."
    permission: "admin.use"
  resetstatistic:
    aliases:
      - statreset
    description: "Réinitialise une statistique du joueur."
    permission: "admin.use"
  updatescoreboard:
    aliases:
      - updatesb
    description: "Met a jour de force le ScoreBoard principal du serveur"
    permission: "admin.use"
  freeze:
    description: "Permet de bloquer tous les mouvements d'un joueur"
  unfreeze:
    description: "Permet de débloquer tous les mouvements d'un joueur"
    permission: "moderateur.use"
  msg:
    description: "Envoyer un message privé"
    permission: "player.use"
  reply:
    description: "Répondre au dernier message privé"
    permission: "player.use"
  togglemp:
    description: "Activer/désactiver la réception des MP"
    permission: "player.use"
  sethome:
    description: "Définit une nouvelle home."
    permission: "player.use"
  home:
    description: "Téléporte à une home."
    permission: "player.use"
  delhome:
    description: "Supprime une home."
    permission: "player.use"
  listhomes:
    description: "Liste vos homes."
    permission: "player.use"
  updatetab:
    description: "Met a jour le tab."
    permission: "moderateur.use"
  updateglobal:
    description: "Met a jour les données du serveur."
    permission: "moderateur.use"
  manage:
    description: "Permet un accès rapide au informations du joueur."
    permission: "moderateur.use"
permissions:
  admin.use:
    default: op
    description: "Permission Administrateur."
    children:
      - "moderateur.use"
      - "helper.use"
      - "vip.use"
      - "player.use"
  moderateur.use:
    default: false
    description: "Permission Modérateur."
    children:
      - "helper.use"
      - "vip.use"
      - "player.use"
  helper.use:
    default: false
    description: "Permission Helper."
    children:
      - "vip.use"
      - "player.use"
  vip.use:
    default: false
    description: "Permission VIP."
    children:
      - "player.use"
  player.use:
    default: true
    description: "Permission Joueur."
